// Field information for context pane - used for UI popups and documentation generation

export type FieldScope = 'document' | 'frame' | 'iframeElement';

export interface FieldInfoEntry {
  label: string;
  scope?: FieldScope;
  description: string;
  technical: string;
  filter: string | null;
}

export const FIELD_INFO: Record<string, FieldInfoEntry> = {
  // Message-level fields (no scope)
  messageId: {
    label: 'Message ID',
    description: 'Unique identifier for this message.',
    technical: 'Generated by the extension when the message event fires in the page context.',
    filter: null
  },
  timestamp: {
    label: 'Timestamp',
    description: 'When the message was received.',
    technical: 'Captured from Date.now() when the message event fires in the page context.',
    filter: null
  },
  dataSize: {
    label: 'Size',
    description: 'Size of the message data when serialized.',
    technical: 'Calculated from JSON.stringify(event.data).length.',
    filter: null
  },
  messageType: {
    label: 'Type',
    description: 'The type field from the message data, if present.',
    technical: 'Extracted from event.data.type if it exists and is a string.',
    filter: 'type:resize'
  },
  buffered: {
    label: 'Buffered',
    description: 'Whether this message was captured before the panel connected.',
    technical: 'Messages sent before DevTools opens are buffered if the page was opened from a monitored tab.',
    filter: null
  },
  sourceType: {
    label: 'Direction',
    description: 'The relationship between the sender and receiver windows.',
    technical: 'Determined by comparing event.source to window.parent, window.opener, opened windows, and child frames.',
    filter: 'sourceType:parent'
  },
  sourceId: {
    label: 'Source ID',
    description: 'Unique identifier assigned to the message source for this session.',
    technical: 'Generated by the content script when first seeing a message from a source. Used to correlate messages with registration data.',
    filter: null
  },

  // Frame-scoped fields
  tabId: {
    label: 'Tab',
    scope: 'frame',
    description: 'The Chrome tab ID of the window.',
    technical: 'Set by the background script from sender.tab.id or the opener relationship registry.',
    filter: null
  },
  frameId: {
    label: 'Frame',
    scope: 'frame',
    description: 'The Chrome frame ID of this window.',
    technical: 'Obtained from sender.frameId in the background script.',
    filter: null
  },
  parentFrameId: {
    label: 'Parent Frame',
    scope: 'frame',
    description: 'The Chrome frame ID of the parent window.',
    technical: 'Obtained from the frame hierarchy via chrome.webNavigation.',
    filter: null
  },
  'tab.openerTab': {
    label: 'Opener Tab',
    scope: 'frame',
    description: 'The tab that opened this tab via window.open.',
    technical: 'Recorded by the background script via chrome.webNavigation.onCreatedNavigationTarget; surfaced to the panel via opener/opened source-type messages and linked into Tab.openerTab.',
    filter: null
  },
  'tab.openedTabs': {
    label: 'Opened Tabs',
    scope: 'frame',
    description: 'Tabs that were opened from this tab via window.open.',
    technical: 'Inverse of openerTab — populated on the opener Tab as opener/opened messages link new tabs.',
    filter: null
  },

  // Document-scoped fields
  'document.documentId': {
    label: 'ID',
    scope: 'document',
    description: 'Chrome-assigned unique identifier for this document instance in the frame.',
    technical: 'Assigned by Chrome via webNavigation API. Changes on each navigation.',
    filter: 'documentId:ABC123'
  },
  'document.url': {
    label: 'URL',
    scope: 'document',
    description: 'The full URL of the document loaded in this frame.',
    technical: 'Obtained from window.location.href of the frame.',
    filter: null
  },
  'document.origin': {
    label: 'Origin',
    scope: 'document',
    description: 'The origin of the document loaded in this frame.',
    technical: 'Obtained from window.location.origin of the frame.',
    filter: 'target:example.com / source:example.com'
  },
  'document.title': {
    label: 'Title',
    scope: 'document',
    description: 'The document title of this frame.',
    technical: 'Obtained from document.title of the frame.',
    filter: null
  },
  'document.createdAt': {
    label: 'Created At',
    scope: 'document',
    description: 'When this FrameDocument was first observed by the panel.',
    technical: 'Captured at FrameDocument construction time via Date.now().',
    filter: null
  },

  // IframeElement-scoped fields (the <iframe> element in the parent document)
  'ownerElement.domPath': {
    label: 'DOM Path',
    scope: 'iframeElement',
    description: 'CSS selector path to the iframe element that contains this frame.',
    technical: 'Obtained via registration message correlation. The parent frame records the iframe domPath when the child registers.',
    filter: null
  },
  'ownerElement.src': {
    label: 'Src',
    scope: 'iframeElement',
    description: 'The src attribute of the iframe element that contains this frame.',
    technical: 'Read from the iframe element in the parent document.',
    filter: null
  },
  'ownerElement.id': {
    label: 'ID',
    scope: 'iframeElement',
    description: 'The id attribute of the iframe element that contains this frame.',
    technical: 'Read from the iframe element in the parent document.',
    filter: null
  },

  // Other unscoped fields
  frameError: {
    label: 'Frame Error',
    description: 'Error that occurred when trying to get frame information.',
    technical: 'Usually indicates the content script could not access frame APIs.',
    filter: null
  },
  partnerFrame: {
    label: 'Partner Frame',
    description: 'The frame ID of the communication partner from the focused frame\'s perspective.',
    technical: 'When Focused Frame is selected, shows the other frame in the message exchange. Empty if focus frame is not involved.',
    filter: null
  },
  partnerType: {
    label: 'Partner Type',
    description: 'The relationship type of the partner frame from the focused frame\'s perspective.',
    technical: 'Shows the relationship (parent, child, opener, opened, etc.) from the focused frame\'s viewpoint. Automatically inverted when focus is the message target.',
    filter: null
  }
};

const SCOPE_PREFIX: Partial<Record<FieldScope, string>> = {
  document: 'Document',
  iframeElement: 'Iframe',
  // 'frame' has no extra prefix
};

// Derive a column label from a column ID.
// For IDs like "target.document.url" or "source.ownerElement.src",
// strips the "target."/"source." prefix, looks up the FIELD_INFO entry,
// and composes:  side + (scope prefix if any) + label.
export function getColumnLabel(colId: string): string {
  for (const sidePrefix of ['target.', 'source.']) {
    if (colId.startsWith(sidePrefix)) {
      const fieldKey = colId.slice(sidePrefix.length);
      const side = sidePrefix === 'target.' ? 'Target' : 'Source';
      const entry = FIELD_INFO[fieldKey];
      if (!entry) return side + ' ' + fieldKey;
      const scopePrefix = entry.scope ? SCOPE_PREFIX[entry.scope] : undefined;
      return scopePrefix
        ? `${side} ${scopePrefix} ${entry.label}`
        : `${side} ${entry.label}`;
    }
  }
  return FIELD_INFO[colId]?.label ?? colId;
}
