// Field information for context pane - used for UI popups and documentation generation

export interface FieldInfoEntry {
  label: string;
  description: string;
  technical: string;
  filter: string | null;
}

export const FIELD_INFO: Record<string, FieldInfoEntry> = {
  // Message-level fields
  messageId: {
    label: 'Message ID',
    description: 'Unique identifier for this message.',
    technical: 'Generated by the extension when the message event fires in the page context.',
    filter: null
  },
  timestamp: {
    label: 'Timestamp',
    description: 'When the message was received.',
    technical: 'Captured from Date.now() when the message event fires in the page context.',
    filter: null
  },
  dataSize: {
    label: 'Size',
    description: 'Size of the message data when serialized.',
    technical: 'Calculated from JSON.stringify(event.data).length.',
    filter: null
  },
  messageType: {
    label: 'Type',
    description: 'The type field from the message data, if present.',
    technical: 'Extracted from event.data.type if it exists and is a string.',
    filter: 'type:resize'
  },
  buffered: {
    label: 'Buffered',
    description: 'Whether this message was captured before the panel connected.',
    technical: 'Messages sent before DevTools opens are buffered if the page was opened from a monitored tab.',
    filter: null
  },
  sourceType: {
    label: 'Source Type',
    description: 'The relationship between the sender and receiver windows.',
    technical: 'Determined by comparing event.source to window.parent, window.opener, opened windows, and child frames.',
    filter: 'sourceType:parent'
  },
  sourceId: {
    label: 'Source ID',
    description: 'Unique identifier assigned to the message source for this session.',
    technical: 'Generated by the content script when first seeing a message from a source. Used to correlate messages with registration data.',
    filter: null
  },

  tabId: {
    label: 'Tab',
    description: 'The Chrome tab ID of the window.',
    technical: 'Set by the background script from sender.tab.id or the opener relationship registry.',
    filter: null
  },

  // Frame/document fields (generic, used by FrameDetail and column label derivation)
  frameId: {
    label: 'Frame',
    description: 'The Chrome frame ID of this window.',
    technical: 'Obtained from sender.frameId in the background script.',
    filter: null
  },
  parentFrameId: {
    label: 'Parent Frame',
    description: 'The Chrome frame ID of the parent window.',
    technical: 'Obtained from the frame hierarchy via chrome.webNavigation.',
    filter: null
  },
  'document.documentId': {
    label: 'Document ID',
    description: 'Chrome-assigned unique identifier for this document instance in the frame.',
    technical: 'Assigned by Chrome via webNavigation API. Changes on each navigation.',
    filter: 'documentId:ABC123'
  },
  'document.url': {
    label: 'Document URL',
    description: 'The full URL of the document loaded in this frame.',
    technical: 'Obtained from window.location.href of the frame.',
    filter: null
  },
  'document.origin': {
    label: 'Document Origin',
    description: 'The origin of the document loaded in this frame.',
    technical: 'Obtained from window.location.origin of the frame.',
    filter: 'target:example.com / source:example.com'
  },
  'document.title': {
    label: 'Document Title',
    description: 'The document title of this frame.',
    technical: 'Obtained from document.title of the frame.',
    filter: null
  },
  'ownerElement.domPath': {
    label: 'Owner Element',
    description: 'CSS selector path to the iframe element that contains this frame.',
    technical: 'Obtained via registration message correlation. The parent frame records the iframe domPath when the child registers.',
    filter: null
  },
  'ownerElement.src': {
    label: 'Iframe Src',
    description: 'The src attribute of the iframe element that contains this frame.',
    technical: 'Read from the iframe element in the parent document.',
    filter: null
  },
  'ownerElement.id': {
    label: 'Iframe ID',
    description: 'The id attribute of the iframe element that contains this frame.',
    technical: 'Read from the iframe element in the parent document.',
    filter: null
  },
  frameError: {
    label: 'Frame Error',
    description: 'Error that occurred when trying to get frame information.',
    technical: 'Usually indicates the content script could not access frame APIs.',
    filter: null
  },
  partnerFrame: {
    label: 'Partner Frame',
    description: 'The frame ID of the communication partner from the focused frame\'s perspective.',
    technical: 'When Focused Frame is selected, shows the other frame in the message exchange. Empty if focus frame is not involved.',
    filter: null
  },
  partnerType: {
    label: 'Partner Type',
    description: 'The relationship type of the partner frame from the focused frame\'s perspective.',
    technical: 'Shows the relationship (parent, child, opener, opened, etc.) from the focused frame\'s viewpoint. Automatically inverted when focus is the message target.',
    filter: null
  }
};

// Derive a column label from a column ID.
// For IDs like "target.document.url" or "source.ownerElement.src",
// strips the prefix and looks up the generic key in FIELD_INFO,
// prepending "Target" or "Source".
export function getColumnLabel(colId: string): string {
  for (const prefix of ['target.', 'source.']) {
    if (colId.startsWith(prefix)) {
      const fieldKey = colId.slice(prefix.length);
      const side = prefix === 'target.' ? 'Target' : 'Source';
      return side + ' ' + (FIELD_INFO[fieldKey]?.label ?? fieldKey);
    }
  }
  return FIELD_INFO[colId]?.label ?? colId;
}
